theme = "kaolin-dark"

[editor]
cursorline = true
color-modes = true
rulers = [120]
auto-pairs = false
mouse = true

[editor.auto-save]
focus-lost = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

left = ["mode", "spinner", "spacer", "version-control"]
center = ["file-name", "file-modification-indicator", "read-only-indicator"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.indent-guides]
render = true
character = "|" # Some characters that work well: "▏", "┆", "┊", "⸽", "╎"
skip-levels = 1

# https://docs.helix-editor.com/master/configuration.html#editorsoft-wrap-section
[editor.soft-wrap]
enable = true
# wrap-at-text-width = true
wrap-indicator = "↩ "

[keys.normal.space]
"F" = "file_picker_in_current_buffer_directory"
"f" = "file_picker"
# "space" = "file_picker"
"space" = "buffer_picker"
"." = "command_mode"

[keys.normal.space."c"]
"o" = ":config-open"
"r" = ":config-reload"

[keys.normal.space."b"]
"r" = ":rl"
"c" = ":bc"
"f" = ":fmt"
"R" = ":rla"
"C" = ":bca"

[keys.normal.space."l"]
"r" = ":lsp-restart"
"w" = ":lsp-workspace-command"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"C-space" = "expand_selection"
"C-A-space" = "shrink_selection"
"C-s" = ":write"
"C-q" = ":quit"
# "C-g" = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazygit"
"C-g" = ":sh kitty @ launch --no-response --cwd $(pwd) --type overlay lazygit"
# "C-e" = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E fx ."
"C-e" = ":sh kitty @ launch --no-response --cwd $(pwd) --type overlay yazi"
# "C-t" = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E"
X = "extend_line_above"
D = "delete_char_backward"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
"C-j" = "normal_mode"
"C-space" = "completion"

# Unimpaired
[keys.normal."æ"]
"d" = "goto_next_diag"
"D" = "goto_last_diag"
"f" = "goto_next_function"
"t" = "goto_next_class"
"a" = "goto_next_parameter"
"c" = "goto_next_comment"
"T" = "goto_next_test"
"p" = "goto_next_paragraph"
"g" = "goto_next_change"
"G" = "goto_last_change"
"space" = "add_newline_below"

[keys.normal."ø"]
"d" = "goto_prev_diag"
"D" = "goto_first_diag"
"f" = "goto_prev_function"
"t" = "goto_prev_class"
"a" = "goto_prev_parameter"
"c" = "goto_prev_comment"
"T" = "goto_prev_test"
"p" = "goto_prev_paragraph"
"g" = "goto_prev_change"
"G" = "goto_first_change"
"space" = "add_newline_above"

