[language-server.unison-nc]
command = "nc"
args = ["localhost", "5757"]

[[language]]
name = "unison"
scope = "source.unison"
injection-regex = "unison"
file-types = ["u"]
shebangs = []
roots = []
auto-format = false
comment-token = "--"
indent = { tab-width = 4, unit = "    " }
language-servers = [
  { name = "unison-nc" }
]

[language-server.roc_ls]
command = "roc_ls"

[[language]]
name = "roc"
scope = "main.roc"
file-types = ["roc"]
shebangs = []
roots = []
auto-format = false
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
language-servers = [
  { name = "roc_ls" }
]

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.eslint.config]
codeActionsOnSave = { mode = "all", "source.fixAll.eslint" = true }
format = { enable = true }
nodePath = ""
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"
experimental = {}
problems = { shortenToSingleLine = false }

[language-server.eslint.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = false }

[language-server.emmet-ls]
command = "emmet-ls"
args = ["--stdio"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
config.hostInfo = "helix"

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "emmet-ls",
  "eslint"
]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "emmet-ls",
  "tailwindcss-ls",
  "eslint"
]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server", "emmet-ls", "eslint" ]
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "emmet-ls", "tailwindcss-ls", "eslint" ]
formatter = { command = "prettier", args = [ "--parser", "jsx" ] }
auto-format = true

[language-server.fsharp-language-server]
# command = "fsharplsp"
command = "/Users/sig/git/fsharp-language-server/src/FSharpLanguageServer/bin/Release/net6.0/FSharpLanguageServer"

[language-server.fs-auto-complete]
command = "dotnet tool fsautocomplete"

[[language]]
name = "fsharp"
auto-format = true
roots = []
# roots = [ "*.fsproj", "*.fsx", ".git" ]
language-servers = [
  { name = "fsharp-language-server" },
  # { name = "fs-auto-complete" },
]

[language-server.postgres-lsp]
command = "postgres_lsp"

[[language]]
name = "sql"
language-servers = [
  { name = "postgres-lsp" }
]
